/*
 * This source file was generated by the Gradle 'init' task
 */
package olspy

import io.ktor.http.*
import kotlinx.coroutines.runBlocking
import java.io.File
import kotlin.test.*

class UsageTest {
    val data = File("src/test/resources/test-data.txt")
        .readLines()
        .map { it.trim() }
        .filter { it.isNotEmpty() && it[0] != '#' }
        .associate {
            val xs = it.split("=", limit = 2)
            xs[0].trimEnd() to xs[1].trimStart()
        }

    val proxy = null // Proxy(Proxy.Type.HTTP, InetSocketAddress("localhost", 8888))
    val conf = ProjectConfig(proxy = proxy, debug = false)

    @Test
    fun openProject() = runBlocking {
        val proj = Project.open(Url(data["share link"]!!), conf)

        require(proj.id == data["project id"]!!)

    }

    @Test
    fun openProjectToken() = runBlocking {
        val proj = Project.open(
            Url(data["base url"]!!),
            data["project id"]!!,
            data["email"]!!,
            data["password"]!!,
            conf
        )

        require(proj.id == data["project id"]!!)
    }

    @Test
    fun testCompile() = runBlocking {
        val proj = Project.open(Url(data["share link"]!!), conf)
        val res = proj.compile()
        println(res)
        assertTrue(res.isSuccessful)
        assertEquals("output.pdf", res.pdf?.path)
    }

    @Test
    fun printTestData()
    {
        println(data)
    }

    @Test
    fun documentGet() = runBlocking {
        println("OPENING PROJECT....")
        val proj = Project.open(Url(data["share link"]!!), conf)
        println("JOINING....")
        val sess = proj.join()
        println("AWAITING INFO....")
        val args = sess.getProjectInfo()

        println(args)
        println("RETRIEVING DOCUMENT....")
        val lines = sess.getDocument(args.project.rootDocID)
        println(lines)

        sess.close()
        println("CLOSED OK")
    }
}
